alias vim='nvim'
alias susp='systemctl suspend'
alias xread='xcalib -red 1.7 1 64 -green 1.7 1 57 -blue 1.7 1 28 -alter'
alias xclear='xcalib -clear'
alias footer='/home/archie/Programming/Scala/Email-footer/email-footer.scala "Santiago Sánchez Fernández" santiago-sánchez-fernández-357701159/ Guisanpea/'
